In [254]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sweetviz as sv
import ydata_profiling as pf
import os , sys
import warnings 
warnings.filterwarnings("ignore")

# **Data Ingestion**

In [255]:
file_path = os.path.join(os.getcwd() , r"dataset\googleplaystore.csv") #file path
#creating dataframe as df 
df=pd.read_csv(file_path) 
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [256]:
#second dataset as df1
df1= pd.read_csv(r"dataset\googleplaystore_user_reviews.csv")
df1.head()

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.00,0.533333
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.25,0.288462
2,10 Best Foods for You,NaN,NaN,NaN,NaN
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.40,0.875000
4,10 Best Foods for You,Best idea us,Positive,1.00,0.300000

In [257]:
#Basic Analysis
print(df.shape)
print(df1.shape)

(10841, 13)
(64295, 5)

In [258]:
#checking column of each dataset , if there is any spaces are not 
print("dataframe 1 columns",df.columns) 
print("\ndataframe 2 columns" , df1.columns)

dataframe 1 columns Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

dataframe 2 columns Index(['App', 'Translated_Review', 'Sentiment', 'Sentiment_Polarity',
       'Sentiment_Subjectivity'],
      dtype='object')

In [259]:
print(df.info()) #checking data types of each columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB
None

In [260]:
df.describe() #only one column is numericals

            Rating
count  9367.000000
mean      4.193338
std       0.537431
min       1.000000
25%       4.000000
50%       4.300000
75%       4.500000
max      19.000000

# **Basic Observation using Automated Library**
**By using Sweeiviz i analyze each columns , after that manually perform EDA***

In [261]:
#lets use automated library for basic observation , i am sweetviz library
#sweetviz_report = sv.analyze(df)
#sweetviz_report.show_html() #for viewing html we need to install ipywidgets

In [262]:
df.isnull().sum()  #rating has more than 1000 null values

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [263]:
df.head() # lets convert these column into numericals , such as Rewiews , Size , installs Price and version

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [264]:
df["Installs"].unique() #lets remove + from install

array(['10,000+', '500,000+', '5,000,000+', '50,000,000+', '100,000+',
       '50,000+', '1,000,000+', '10,000,000+', '5,000+', '100,000,000+',
       '1,000,000,000+', '1,000+', '500,000,000+', '50+', '100+', '500+',
       '10+', '1+', '5+', '0+', '0', 'Free'], dtype=object)

In [265]:
# Function to handle the conversion
def convert_to_numeric(value):
    if value == 'Free':
        return 0
    else:
        # Remove commas and '+'
        value = value.replace(',', '').replace('+', '')
        return int(value)

# Apply the conversion
df["Installs"] = df["Installs"].apply(convert_to_numeric)

In [266]:
df["Installs"].unique() #its looking fine

array([     10000,     500000,    5000000,   50000000,     100000,
            50000,    1000000,   10000000,       5000,  100000000,
       1000000000,       1000,  500000000,         50,        100,
              500,         10,          1,          5,          0],
      dtype=int64)

In [267]:
df["Installs"].isnull().sum() #no null values

0

In [268]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,10000,Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,500000,Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,5000000,Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,50000000,Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,100000,Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [269]:
df["Price"].unique() #lets remove this dollar sign $ from Price column

array(['0', '$4.99', '$3.99', '$6.99', '$1.49', '$2.99', '$7.99', '$5.99',
       '$3.49', '$1.99', '$9.99', '$7.49', '$0.99', '$9.00', '$5.49',
       '$10.00', '$24.99', '$11.99', '$79.99', '$16.99', '$14.99',
       '$1.00', '$29.99', '$12.99', '$2.49', '$10.99', '$1.50', '$19.99',
       '$15.99', '$33.99', '$74.99', '$39.99', '$3.95', '$4.49', '$1.70',
       '$8.99', '$2.00', '$3.88', '$25.99', '$399.99', '$17.99',
       '$400.00', '$3.02', '$1.76', '$4.84', '$4.77', '$1.61', '$2.50',
       '$1.59', '$6.49', '$1.29', '$5.00', '$13.99', '$299.99', '$379.99',
       '$37.99', '$18.99', '$389.99', '$19.90', '$8.49', '$1.75',
       '$14.00', '$4.85', '$46.99', '$109.99', '$154.99', '$3.08',
       '$2.59', '$4.80', '$1.96', '$19.40', '$3.90', '$4.59', '$15.46',
       '$3.04', '$4.29', '$2.60', '$3.28', '$4.60', '$28.99', '$2.95',
       '$2.90', '$1.97', '$200.00', '$89.99', '$2.56', '$30.99', '$3.61',
       '$394.99', '$1.26', 'Everyone', '$1.20', '$1.04'], dtype=object)

**for this i will remove $ sign and remove Everyone Label with 0**

In [270]:
df["Price"]= df["Price"].str.replace("$" , "")
df["Price"]= df["Price"].str.replace("Everyone" , "0")
df["Price"]=df["Price"].astype(float)
df["Price"].unique()
df.rename(columns={"Price":"Price($)"} , inplace=True)
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price($),Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,10000,Free,0.0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,500000,Free,0.0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,5000000,Free,0.0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,50000000,Free,0.0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,100000,Free,0.0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [271]:
df["Size"].unique() #checking unique values inside size column

array(['19M', '14M', '8.7M', '25M', '2.8M', '5.6M', '29M', '33M', '3.1M',
       '28M', '12M', '20M', '21M', '37M', '2.7M', '5.5M', '17M', '39M',
       '31M', '4.2M', '7.0M', '23M', '6.0M', '6.1M', '4.6M', '9.2M',
       '5.2M', '11M', '24M', 'Varies with device', '9.4M', '15M', '10M',
       '1.2M', '26M', '8.0M', '7.9M', '56M', '57M', '35M', '54M', '201k',
       '3.6M', '5.7M', '8.6M', '2.4M', '27M', '2.5M', '16M', '3.4M',
       '8.9M', '3.9M', '2.9M', '38M', '32M', '5.4M', '18M', '1.1M',
       '2.2M', '4.5M', '9.8M', '52M', '9.0M', '6.7M', '30M', '2.6M',
       '7.1M', '3.7M', '22M', '7.4M', '6.4M', '3.2M', '8.2M', '9.9M',
       '4.9M', '9.5M', '5.0M', '5.9M', '13M', '73M', '6.8M', '3.5M',
       '4.0M', '2.3M', '7.2M', '2.1M', '42M', '7.3M', '9.1M', '55M',
       '23k', '6.5M', '1.5M', '7.5M', '51M', '41M', '48M', '8.5M', '46M',
       '8.3M', '4.3M', '4.7M', '3.3M', '40M', '7.8M', '8.8M', '6.6M',
       '5.1M', '61M', '66M', '79k', '8.4M', '118k', '44M', '695k', '1.6M',
       '6.2M', '18k', '53M', '1.4M', '3.0M', '5.8M', '3.8M', '9.6M',
       '45M', '63M', '49M', '77M', '4.4M', '4.8M', '70M', '6.9M', '9.3M',
       '10.0M', '8.1M', '36M', '84M', '97M', '2.0M', '1.9M', '1.8M',
       '5.3M', '47M', '556k', '526k', '76M', '7.6M', '59M', '9.7M', '78M',
       '72M', '43M', '7.7M', '6.3M', '334k', '34M', '93M', '65M', '79M',
       '100M', '58M', '50M', '68M', '64M', '67M', '60M', '94M', '232k',
       '99M', '624k', '95M', '8.5k', '41k', '292k', '11k', '80M', '1.7M',
       '74M', '62M', '69M', '75M', '98M', '85M', '82M', '96M', '87M',
       '71M', '86M', '91M', '81M', '92M', '83M', '88M', '704k', '862k',
       '899k', '378k', '266k', '375k', '1.3M', '975k', '980k', '4.1M',
       '89M', '696k', '544k', '525k', '920k', '779k', '853k', '720k',
       '713k', '772k', '318k', '58k', '241k', '196k', '857k', '51k',
       '953k', '865k', '251k', '930k', '540k', '313k', '746k', '203k',
       '26k', '314k', '239k', '371k', '220k', '730k', '756k', '91k',
       '293k', '17k', '74k', '14k', '317k', '78k', '924k', '902k', '818k',
       '81k', '939k', '169k', '45k', '475k', '965k', '90M', '545k', '61k',
       '283k', '655k', '714k', '93k', '872k', '121k', '322k', '1.0M',
       '976k', '172k', '238k', '549k', '206k', '954k', '444k', '717k',
       '210k', '609k', '308k', '705k', '306k', '904k', '473k', '175k',
       '350k', '383k', '454k', '421k', '70k', '812k', '442k', '842k',
       '417k', '412k', '459k', '478k', '335k', '782k', '721k', '430k',
       '429k', '192k', '200k', '460k', '728k', '496k', '816k', '414k',
       '506k', '887k', '613k', '243k', '569k', '778k', '683k', '592k',
       '319k', '186k', '840k', '647k', '191k', '373k', '437k', '598k',
       '716k', '585k', '982k', '222k', '219k', '55k', '948k', '323k',
       '691k', '511k', '951k', '963k', '25k', '554k', '351k', '27k',
       '82k', '208k', '913k', '514k', '551k', '29k', '103k', '898k',
       '743k', '116k', '153k', '209k', '353k', '499k', '173k', '597k',
       '809k', '122k', '411k', '400k', '801k', '787k', '237k', '50k',
       '643k', '986k', '97k', '516k', '837k', '780k', '961k', '269k',
       '20k', '498k', '600k', '749k', '642k', '881k', '72k', '656k',
       '601k', '221k', '228k', '108k', '940k', '176k', '33k', '663k',
       '34k', '942k', '259k', '164k', '458k', '245k', '629k', '28k',
       '288k', '775k', '785k', '636k', '916k', '994k', '309k', '485k',
       '914k', '903k', '608k', '500k', '54k', '562k', '847k', '957k',
       '688k', '811k', '270k', '48k', '329k', '523k', '921k', '874k',
       '981k', '784k', '280k', '24k', '518k', '754k', '892k', '154k',
       '860k', '364k', '387k', '626k', '161k', '879k', '39k', '970k',
       '170k', '141k', '160k', '144k', '143k', '190k', '376k', '193k',
       '246k', '73k', '658k', '992k', '253k', '420k', '404k', '1,000+',
       '470k', '226k', '240k', '89k', '234k', '257k', '861k', '467k',
       '157k', '44k', '676k', '67k', '552k', '885k', '1020k', '582k',
       '619k'], dtype=object)

In [272]:
# Function to convert sizes
def convert_size(size):
    if isinstance(size, str):
        size = size.upper()  # Ensure 'M' and 'K' are uppercase for consistency
        if "M" in size:
            return float(size.replace("M", "")) * 1000  # Convert MB to KB
        elif "K" in size:
            return float(size.replace("K", ""))  # Keep KB as is
        else:
            return np.nan  # Handle 'Varies with device' or other unexpected formats
    else:
        return np.nan  # Handle NaN or other non-string entries

# Apply the function to the 'Size' column
df["Size"] = df["Size"].apply(convert_size)
# Check the output
print(df["Size"].head(10))

0    19000.0
1    14000.0
2     8700.0
3    25000.0
4     2800.0
5     5600.0
6    19000.0
7    29000.0
8    33000.0
9     3100.0
Name: Size, dtype: float64

In [273]:
df["Size"].isnull().sum()
df["Size"]= df["Size"].replace(np.nan , df["Size"].mean()) #replacing null values with mean of Size column 
print(df["Size"].isnull().sum())
df.rename(columns={"Size":"Size(kb)"} , inplace=True)  #Changing column name in kb

0

In [274]:
df["Android Ver"].unique() #lets extract num and else be removed

array(['4.0.3 and up', '4.2 and up', '4.4 and up', '2.3 and up',
       '3.0 and up', '4.1 and up', '4.0 and up', '2.3.3 and up',
       'Varies with device', '2.2 and up', '5.0 and up', '6.0 and up',
       '1.6 and up', '1.5 and up', '2.1 and up', '7.0 and up',
       '5.1 and up', '4.3 and up', '4.0.3 - 7.1.1', '2.0 and up',
       '3.2 and up', '4.4W and up', '7.1 and up', '7.0 - 7.1.1',
       '8.0 and up', '5.0 - 8.0', '3.1 and up', '2.0.1 and up',
       '4.1 - 7.1.1', nan, '5.0 - 6.0', '1.0 and up', '2.2 - 7.1.1',
       '5.0 - 7.1.1'], dtype=object)

In [275]:
# Function to convert version strings and keep only major.minor (e.g., '4.0.3' -> 4.0)
def convert_version(value):
    if pd.isna(value) or value == 'Varies with device':
        return np.nan  # Representing missing data
    elif 'and up' in value:
        version = value.split(' and up')[0].replace('W', '').strip()
    elif '-' in value:
        version = value.split('-')[0].replace('W', '').strip()
    else:
        version = value.replace('W', '').strip()

    # Split the version by '.' and take the major and minor parts (first two parts)
    version_parts = version.split('.')
    major_minor = '.'.join(version_parts[:2])  # Keep only major and minor parts
    
    return float(major_minor)  # Convert to float for numeric operations

# Apply the function to the 'Android Ver' column
df['Android Ver'] = df['Android Ver'].apply(convert_version)

# Check the output
print(df['Android Ver'].head())

0    4.0
1    4.0
2    4.0
3    4.2
4    4.4
Name: Android Ver, dtype: float64

In [276]:
df = df.dropna(subset=['Android Ver']) #droping nan values 
df.shape

(9476, 13)

In [277]:
df.isnull().sum()

App                  0
Category             0
Rating            1431
Reviews              0
Size(kb)             0
Installs             0
Type                 0
Price($)             0
Content Rating       0
Genres               0
Last Updated         0
Current Ver          8
Android Ver          0
dtype: int64

In [278]:
#lets handle this Null values inside Rating Column
df["Rating"]= df["Rating"].replace(np.nan , df["Rating"].mean())
df["Rating"].isnull().sum()

0

In [279]:
df["Current Ver"]

0                     1.0.0
1                     2.0.0
2                     1.2.4
3        Varies with device
4                       1.1
                ...
10834                 1.0.0
10835                 1.1.5
10836                  1.48
10837                   1.0
10838                   1.0
Name: Current Ver, Length: 9476, dtype: object

In [280]:
import re
# Function to convert version strings and keep only major.minor (e.g., '1.2.4' -> 1.2)
def convert_version(value):
    if pd.isna(value) or value == 'Varies with device':
        return np.nan  # Representing missing data
    else:
        # Use regex to find the first valid version number with major.minor format
        match = re.match(r'(\d+\.\d+)', value)  # Extract only the first two numeric parts
        if match:
            return float(match.group(1))  # Convert to float for numeric operations
        else:
            return np.nan  # If no valid version format is found, return NaN

# Apply the function to the 'Version' column
df['Current Ver'] = df['Current Ver'].apply(convert_version)
df['Current Ver']= df["Current Ver"].replace(np.nan ,df["Current Ver"].median() ) #replacing NaN with middle value

In [281]:
df['Current Ver']

0        1.00
1        2.00
2        1.20
3        1.90
4        1.10
         ...
10834    1.00
10835    1.10
10836    1.48
10837    1.00
10838    1.00
Name: Current Ver, Length: 9476, dtype: float64

In [282]:
df["App"] = df["App"].replace("," , "")

In [283]:
df.head()

,App,Category,Rating,Reviews,Size(kb),Installs,Type,Price($),Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19000.0,10000,Free,0.0,Everyone,Art & Design,"January 7, 2018",1.0,4.0
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14000.0,500000,Free,0.0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0,4.0
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8700.0,5000000,Free,0.0,Everyone,Art & Design,"August 1, 2018",1.2,4.0
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25000.0,50000000,Free,0.0,Teen,Art & Design,"June 8, 2018",1.9,4.2
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2800.0,100000,Free,0.0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4

In [284]:
df['Last Updated']

0           January 7, 2018
1          January 15, 2018
2            August 1, 2018
3              June 8, 2018
4             June 20, 2018
                ...
10834         June 18, 2017
10835    September 29, 2016
10836         July 25, 2017
10837          July 6, 2018
10838      January 20, 2017
Name: Last Updated, Length: 9476, dtype: object

In [285]:
#Converting last updated to pd.datetime , after that creating  two new columns month and year using datetime
df["update_date"]=pd.to_datetime(df["Last Updated"])
df.drop("Last Updated" , axis=1 , inplace=True) #droping last updated column from a dataframe
df["Month"]=df["update_date"].dt.month 
df["Year"]=df["update_date"].dt.year
df.head(2)

,App,Category,Rating,Reviews,Size(kb),Installs,Type,Price($),Content Rating,Genres,Current Ver,Android Ver,update_date,Month,Year
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19000.0,10000,Free,0.0,Everyone,Art & Design,1.0,4.0,2018-01-07,1,2018
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14000.0,500000,Free,0.0,Everyone,Art & Design;Pretend Play,2.0,4.0,2018-01-15,1,2018

In [286]:
df.info()
df.to_csv("dataset/clean_googleplay.csv" , index=False) #saving clean dataset

<class 'pandas.core.frame.DataFrame'>
Index: 9476 entries, 0 to 10838
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             9476 non-null   object
 1   Category        9476 non-null   object
 2   Rating          9476 non-null   float64
 3   Reviews         9476 non-null   object
 4   Size(kb)        9476 non-null   float64
 5   Installs        9476 non-null   int64
 6   Type            9476 non-null   object
 7   Price($)        9476 non-null   float64
 8   Content Rating  9476 non-null   object
 9   Genres          9476 non-null   object
 10  Current Ver     9476 non-null   float64
 11  Android Ver     9476 non-null   float64
 12  update_date     9476 non-null   datetime64[ns]
 13  Month           9476 non-null   int32
 14  Year            9476 non-null   int32
dtypes: datetime64[ns](1), float64(5), int32(2), int64(1), object(6)
memory usage: 1.1+ MB

# **lets separate Categorical and numberical columns**

In [287]:
df_copy = df.copy()  #creating copy of original dataset

In [288]:
df_copy.drop("update_date" , axis=1 , inplace=True) #droping unwanted column 
categ_column = [columns for columns in df_copy.columns if df_copy[columns].dtype=="O"] #Categorical column
num_column = [columns for columns in df_copy.columns if df_copy[columns].dtype!="O"] #numerical column 
print(categ_column)
print(num_column)

['App', 'Category', 'Reviews', 'Type', 'Content Rating', 'Genres']
['Rating', 'Size(kb)', 'Installs', 'Price($)', 'Current Ver', 'Android Ver', 'Month', 'Year']

In [289]:
print(df_copy[num_column].head(2))

   Rating  Size(kb)  Installs  Price($)  Current Ver  Android Ver  Month  Year
0     4.1   19000.0     10000       0.0          1.0          4.0      1  2018
1     3.9   14000.0    500000       0.0          2.0          4.0      1  2018

In [290]:
print(df_copy[categ_column].head(2))

                                              App        Category Reviews  \
0  Photo Editor & Candy Camera & Grid & ScrapBook  ART_AND_DESIGN     159
1                             Coloring book moana  ART_AND_DESIGN     967

   Type Content Rating                     Genres
0  Free       Everyone               Art & Design
1  Free       Everyone  Art & Design;Pretend Play

# ***lets clean Second Dataframe User Review***

In [291]:
df1.head()

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.00,0.533333
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.25,0.288462
2,10 Best Foods for You,NaN,NaN,NaN,NaN
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.40,0.875000
4,10 Best Foods for You,Best idea us,Positive,1.00,0.300000

In [292]:
df1.isnull().sum() #Each column has exactly same no. of null values , lets just drop it

App                           0
Translated_Review         26868
Sentiment                 26863
Sentiment_Polarity        26863
Sentiment_Subjectivity    26863
dtype: int64

In [293]:
df1.dropna(inplace=True)
print(df1.isnull().sum())
print("\n No. of rows and column :", df1.shape)

App                       0
Translated_Review         0
Sentiment                 0
Sentiment_Polarity        0
Sentiment_Subjectivity    0
dtype: int64

 No. of rows and column : (37427, 5)

In [294]:
df1.describe()

       Sentiment_Polarity  Sentiment_Subjectivity
count        37427.000000            37427.000000
mean             0.182171                0.492770
std              0.351318                0.259904
min             -1.000000                0.000000
25%              0.000000                0.357143
50%              0.150000                0.514286
75%              0.400000                0.650000
max              1.000000                1.000000

In [295]:
df1.duplicated().sum()
df1.drop_duplicates(inplace=True)
print(df1.duplicated().sum()) #no duplicates values

0

In [296]:
#lets convert numericals  column into float , there are two numericals columns
df1[["Sentiment_Polarity" , "Sentiment_Subjectivity"]] = df1[["Sentiment_Polarity" , "Sentiment_Subjectivity"]].astype(float)
df1[["Sentiment_Polarity" , "Sentiment_Subjectivity"]].info()

<class 'pandas.core.frame.DataFrame'>
Index: 29692 entries, 0 to 64230
Data columns (total 2 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Sentiment_Polarity      29692 non-null  float64
 1   Sentiment_Subjectivity  29692 non-null  float64
dtypes: float64(2)
memory usage: 695.9 KB

In [297]:
df1["Translated_Review"].unique()

array(['I like eat delicious food. That\'s I\'m cooking food myself, case "10 Best Foods" helps lot, also "Best Before (Shelf Life)"',
       'This help eating healthy exercise regular basis',
       'Works great especially going grocery store', ...,
       'Dumb app, I wanted post property rent give option. Website work. Waste time space phone.',
       'I property business got link SMS happy performance still guys need raise bar guys Cheers',
       'Useless app, I searched flats kondapur, Hyderabad . None number reachable I know flats unavailable would keep posts active'],
      dtype=object)

In [298]:
df1.drop("Translated_Review" ,axis=1 , inplace=True) # unnecessary column

In [299]:
df1.head()
df1_copy = df1.copy()

# **Exploratory Data Analysis**

In [300]:
df_copy[num_column].head()

   Rating  Size(kb)  Installs  Price($)  Current Ver  Android Ver  Month  Year
0     4.1   19000.0     10000       0.0          1.0          4.0      1  2018
1     3.9   14000.0    500000       0.0          2.0          4.0      1  2018
2     4.7    8700.0   5000000       0.0          1.2          4.0      8  2018
3     4.5   25000.0  50000000       0.0          1.9          4.2      6  2018
4     4.3    2800.0    100000       0.0          1.1          4.4      6  2018

In [301]:
df_copy[].head()

,App,Category,Reviews,Type,Content Rating,Genres
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,159,Free,Everyone,Art & Design
1,Coloring book moana,ART_AND_DESIGN,967,Free,Everyone,Art & Design;Pretend Play
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,87510,Free,Everyone,Art & Design
3,Sketch - Draw & Paint,ART_AND_DESIGN,215644,Free,Teen,Art & Design
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,967,Free,Everyone,Art & Design;Creativity

In [329]:
app = df["App"]

In [330]:
sns.set_style("darkgrid")
sns.barplot(y=app.index , x=app.values)