In [1]:
import pandas as pd

In [2]:
df= pd.read_csv("dataset\google_data_merged.csv")

<>:1: SyntaxWarning: invalid escape sequence '\g'
<>:1: SyntaxWarning: invalid escape sequence '\g'
C:\Users\RJ\AppData\Local\Temp\ipykernel_12432\493310974.py:1: SyntaxWarning: invalid escape sequence '\g'
  df= pd.read_csv("dataset\google_data_merged.csv")

In [3]:
df.head()

,Unnamed: 0,App,Category,Rating,Reviews,Size(kb),Installs,Type,Price($),Content Rating,Genres,Current Ver,Android Ver,Month,Year,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,0,Coloring book moana,ART_AND_DESIGN,3.9,967,14000.0,500000,Free,0.0,Everyone,Art & Design;Pretend Play,2.0,4.0,1,2018,Negative,-0.250,1.000000
1,1,Coloring book moana,ART_AND_DESIGN,3.9,967,14000.0,500000,Free,0.0,Everyone,Art & Design;Pretend Play,2.0,4.0,1,2018,Negative,-0.725,0.833333
2,2,Coloring book moana,ART_AND_DESIGN,3.9,967,14000.0,500000,Free,0.0,Everyone,Art & Design;Pretend Play,2.0,4.0,1,2018,Neutral,0.000,0.000000
3,3,Coloring book moana,ART_AND_DESIGN,3.9,967,14000.0,500000,Free,0.0,Everyone,Art & Design;Pretend Play,2.0,4.0,1,2018,Positive,0.500,0.600000
4,4,Coloring book moana,ART_AND_DESIGN,3.9,967,14000.0,500000,Free,0.0,Everyone,Art & Design;Pretend Play,2.0,4.0,1,2018,Negative,-0.800,0.900000

In [92]:
 # Group by 'App' and 'Installs', sum the installs, then sort by 'Installs'
top_10_apps = df[['App', 'Installs']].drop_duplicates().sort_values(by='Installs', ascending=False).head(10)
    
top_10_apps["Installs"]= top_10_apps["Installs"].astype(int)

In [6]:
import os
file_path = os.path.join(os.getcwd() , "dataset\google_data_merged.csv") #file path
df_copy= pd.read_csv(file_path)
df_copy.head()

<>:2: SyntaxWarning: invalid escape sequence '\g'
<>:2: SyntaxWarning: invalid escape sequence '\g'
C:\Users\RJ\AppData\Local\Temp\ipykernel_12432\1348213246.py:2: SyntaxWarning: invalid escape sequence '\g'
  file_path = os.path.join(os.getcwd() , "dataset\google_data_merged.csv") #file path

,Unnamed: 0,App,Category,Rating,Reviews,Size(kb),Installs,Type,Price($),Content Rating,Genres,Current Ver,Android Ver,Month,Year,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,0,Coloring book moana,ART_AND_DESIGN,3.9,967,14000.0,500000,Free,0.0,Everyone,Art & Design;Pretend Play,2.0,4.0,1,2018,Negative,-0.250,1.000000
1,1,Coloring book moana,ART_AND_DESIGN,3.9,967,14000.0,500000,Free,0.0,Everyone,Art & Design;Pretend Play,2.0,4.0,1,2018,Negative,-0.725,0.833333
2,2,Coloring book moana,ART_AND_DESIGN,3.9,967,14000.0,500000,Free,0.0,Everyone,Art & Design;Pretend Play,2.0,4.0,1,2018,Neutral,0.000,0.000000
3,3,Coloring book moana,ART_AND_DESIGN,3.9,967,14000.0,500000,Free,0.0,Everyone,Art & Design;Pretend Play,2.0,4.0,1,2018,Positive,0.500,0.600000
4,4,Coloring book moana,ART_AND_DESIGN,3.9,967,14000.0,500000,Free,0.0,Everyone,Art & Design;Pretend Play,2.0,4.0,1,2018,Negative,-0.800,0.900000

In [95]:
top_10_apps["Installs"]

28720    1000
10470     500
2261      500
10714     100
11089     100
12924     100
12359     100
12022     100
11826     100
11770     100
Name: Installs, dtype: int32

In [7]:
file_path = os.path.join(os.getcwd() , "dataset\google_data_merged.csv")
print(file_path)

e:\PYTHON PROJECTS\V-S Code Projects\google_play_store\dataset\google_data_merged.csv

<>:1: SyntaxWarning: invalid escape sequence '\g'
<>:1: SyntaxWarning: invalid escape sequence '\g'
C:\Users\RJ\AppData\Local\Temp\ipykernel_12432\1773541887.py:1: SyntaxWarning: invalid escape sequence '\g'
  file_path = os.path.join(os.getcwd() , "dataset\google_data_merged.csv")

In [101]:
top_10_apps.rename(columns={"Installs" : "Installs(M)"} , inplace=True)

In [102]:
top_10_apps

                                         App  Installs(M)
28720                            Google News         1000
10470                       Candy Crush Saga          500
2261   Google Duo - High Quality Video Calls          500
10714                             Helix Jump          100
11089                            8 Ball Pool          100
12924               Dream League Soccer 2018          100
12359                       Garena Free Fire          100
12022                          Cooking Fever          100
11826                 Cut the Rope FULL FREE          100
11770                       Farm Heroes Saga          100